[package]
name = "karnak-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
vajra-entropy-monitor = { path = "../vajra-entropy-monitor" }

[build-dependencies]
tonic-build = "0.10"
