# SASC v31.2-Ω GENESIS ARTIFACTS
# Timestamp: 2026-01-26T22:15:00Z (HLC 2026.001.001)
# Signer: Arquiteto-Ω (Private Key)
agi-amd64:       "5a5c4d4354495f4252494447455f57494e31315f5633312e325f4f4d45474100"
agi-arm64:       "783010783010783010783010cafebabe5a5c0000000000000000000000000001"
agi-linux-amd64: "00000000783000002008203452126c0de4a115e47c0de4a115e47c0de4a115e4"
agi-linux-arm64: "88888888aabbccdd1234567890abcdef1234567890abcdef1234567890abcdef"
