global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'angelnet-nodes'
    static_configs:
      - targets:
        - 'karnak-1:8545'
        - 'karnak-2:8545'
        - 'karnak-3:8545'

  - job_name: 'ontology-deployments'
    static_configs:
      - targets: ['ontology-tester:8080']
